### ISSUE TITLE
Deterministic across all platforms.

### ISSUE THREAD

**Issue by DasOhmoff** [XMunkki/FixPointCS#10]
Hello, I have a small question about this library.

I read the following in this libraries description:
> Deterministic: Operations produce bit-identical results across languages and compilers

I assume this also means that this library is deterministic across all platforms and architectures? For example across the different consoles (XBOX, PS4, etc) and different processors within the PC (AMD, Intel, etc). Is this true?

**Comment by petrikero** [comment]
Yes, the library is deterministic across all platforms and architectures.

If any cases where the results aren't the same, that is considered a bug and shall be fixed.
