### ISSUE TITLE
Fixed64.FromFloat() result casted to int instead of long, causing wrong values

### ISSUE THREAD

**Issue by eeroh** [XMunkki/FixPointCS#2]
The function
```
public static long FromFloat(float v)
{
    return (int)(v * 4294967296.0f);
}
```
in `Fixed64` ought to cast with `(long)` instead. Otherwise the result often exceeds int value bounds, causing unexpected results.

**Comment by petrikero** [comment]
Good catch! I just pushed a fix into master.
