### ISSUE TITLE
Mod() operation

### ISSUE THREAD

**Issue by ansstuff** [XMunkki/FixPointCS#8]
I'm a bit puzzled, what's the reason for implementing the modulo function this way?

```
        public static long Mod(long a, long b)
        {
            long di = a / b;
            long ret = a - (di * b);
            return ret;
        }
```

Isn't it more performant to just use existing % operator?

```
        public static long Mod(long a, long b)
        {
            long ret = a % b;
            return ret;
        }
```

As far as I understand, there should not be any difference in result of calculation.

Also, the function needs input check:
```
            if (b == 0)
            {
                FixedUtil.InvalidArgument("Fixed64.Mod", "b", b);
                return 0;
            }
```
(b == MinValue case works well with Mod)

**Comment by petrikero** [comment]
Took a while, but now fixed. Thanks for reporting!
